### ISSUE TITLE
marshal.rb:6:in `load': marshal data too short (ArgumentError)

### ISSUE THREAD

**Issue by aaronsevers** [steel/sprockets-derailleur#16]
I've been seeing this error intermittently while precompiling assets with sprockets-derailleur for a few weeks now... possibly since Rails 4.1.7... any idea what could be causing it?

```
/home/rof/cache/bundler/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/marshal.rb:6:in `load': marshal data too short (ArgumentError)
    from /home/rof/cache/bundler/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/cache/file_store.rb:19:in `block in []'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/cache/file_store.rb:19:in `open'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/cache/file_store.rb:19:in `open'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/cache/file_store.rb:19:in `[]'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:14:in `cache_get'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:84:in `cache_get_hash'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:54:in `cache_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `each'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:16:in `initialize'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:101:in `block (2 levels) in worker'
    from /home/rof/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:98:in `block in worker'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:90:in `fork'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:90:in `worker'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:30:in `block (2 levels) in compile'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:29:in `times'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:29:in `block in compile'
    from /home/rof/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:10:in `compile'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-rails-2.2.1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-rails-2.2.1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:240:in `block in execute'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:235:in `execute'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
    from /home/rof/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/task.rb:165:in `invoke'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:156:in `invoke_task'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:112:in `block (2 levels) in top_level'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:112:in `each'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:112:in `block in top_level'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:121:in `run_with_threads'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:106:in `top_level'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:84:in `block in run'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:182:in `standard_exception_handling'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/lib/rake/application.rb:79:in `run'
    from /home/rof/cache/bundler/ruby/2.1.0/gems/rake-10.4.0/bin/rake:33:in `<top (required)>'
    from /home/rof/cache/bundler/ruby/2.1.0/bin/rake:23:in `load'
    from /home/rof/cache/bundler/ruby/2.1.0/bin/rake:23:in `<main>'
rake aborted!
EOFError: end of file reached
/home/rof/cache/bundler/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/marshal.rb:6:in `load'
/home/rof/cache/bundler/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:45:in `block (3 levels) in compile'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:44:in `each'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:44:in `block (2 levels) in compile'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:39:in `loop'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:39:in `block in compile'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:10:in `compile'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-rails-2.2.1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-rails-2.2.1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
/home/rof/cache/bundler/ruby/2.1.0/gems/sprockets-derailleur-0.0.9/lib/sprockets-derailleur/manifest.rb:121:in `write': Broken pipe (Errno::EPIPE)
```

**Comment by akayvanfar** [comment]
I am experiencing this error as well. Solution in ReadMe are not helping.

**Comment by puneeth-k** [comment]
Still an issue, we are also facing the same problem.
We are facing the issue still. Troubleshooting instructions are not helping either.

Broken pipe (Errno::EPIPE) Error with Ruby 2.3.1 & Rails 5.0.2 Assets Precompile

gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:122:in `write': Broken pipe (Errno::EPIPE)
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:122:in `dump'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:122:in `block (3 levels) in worker'
	from /gems/sprockets-3.7.1/lib/sprockets/manifest.rb:135:in `block (2 levels) in find'
	from /gems/sprockets-3.7.1/lib/sprockets/base.rb:80:in `find_all_linked_assets'
	from /gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
	from /gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
	from /gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:103:in `each'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:103:in `block (2 levels) in worker'
	from /Users/dashbitla/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:100:in `block in worker'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:92:in `fork'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:92:in `worker'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:32:in `block (2 levels) in compile'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:31:in `times'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:31:in `block in compile'
	from /Users/dashbitla/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
	from /gems/sprockets-derailleur-1.1.0/lib/sprockets-derailleur/manifest.rb:12:in `compile'
	from /gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
	from /gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
	from /gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
	from /gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
	from /gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
	from /gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
	from /gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
	from /Users/dashbitla/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
	from /gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
	from /gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
	from /gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
	from /gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
	from /gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
	from /gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
	from /gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
	from /gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
	from /gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
	from /gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
	from /gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
	from /bin/rake:23:in `load'
	from /bin/rake:23:in `<main>'
	from /bin/ruby_executable_hooks:15:in `eval'
	from /bin/ruby_executable_hooks:15:in `<main>'
W, [2017-06-15T12:14:50.068757 #67075]  WARN -- : Completed compiling assets (3.54s)

Used the following configuration and tried as well.

The default cache is not safe for parallel, you can override it by adding the following to config/application.rb:

config.assets.configure do |env|
  env.cache = SprocketsDerailleur::FileStore.new("tmp/cache/assets")
end
